### ISSUE TITLE
Problems with path names when running under Linux (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by RobBlackwell** [Cytobuoy/CyzFile-API#1]
Running `CyzFileDump.exe` with no arguments works under Linux (Windows Subsystem for Linux). E.g.,

```
reb@3XD7HW3:/mnt/c/Users/RB26/git/build/bin/CyzFile-API/CyzFileDump/AnyCPU/Debug/net7.0$ ./CyzFileDump.exe
SYNOPSIS

    CyzDumpFile [options] <filename>.cyz

DESCRIPTION

    This is an example on using the CyzFile library it is not meant to be
    be a useful standalone program. It could be the start of one, but it is
    not at the moment.

    Extract information from the data file and dump it into a file or to the
    console.

OPTIONS

    -h   - Display this help screen.
    -i   - Output some basic information.
    -p   - Display particle information (only the first 1000).
    -m   - iMages output the images as JPEG into the current folder.


EXAMPLES

 CyzFileDump -h
 CyzFileDump -i MyDataFile.cyz
 CyzFileDump -i -p -m MyDataFile.cyz
 CyzFileDump -ip MyDataFile.cyz
 CyzFileDump -ip -m MyDataFile.cyz
 CyzFileDump -ipm MyDataFile.cyz
```

However, when I try to run `CyzFileDump.exe` on a CYZ file in the current directory, it fails

```
reb@3XD7HW3:/mnt/c/Users/RB26/git/build/bin/CyzFile-API/CyzFileDump/AnyCPU/Debug/net7.0$ ./CyzFileDump.exe -i Pond_NA/Pond_NA\ 2023-05-24\ 09h23.cyz
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\RB26\git\build\bin\CyzFile-API\CyzFileDump\AnyCPU\Debug\net7
.0\Pond_NA\Pond_NA 2023-05-24 09h23.cyz'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationS
ize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize,
 Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 prealloc
ationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at CytoSense.Serializing.Serializing.loadFromFile(String filename) in C:\Users\RB26\git\CyzFile-API\CyzFile\Serializing\Serializing.vb:line 71
   at CytoSense.Serializing.Serializing.loadFromFile[T](String filename) in C:\Users\RB26\git\CyzFile-API\CyzFile\Serializing\Serializing.vb:line 64
   at CytoSense.Data.DataFunctions.loadDatafile(String path) in C:\Users\RB26\git\CyzFile-API\CyzFile\Data\DataFunctions.vb:line 241
   at CytoSense.Data.DataFileWrapper..ctor(String filename, Boolean DisableParallism) in C:\Users\RB26\git\CyzFile-API\CyzFile\Data\DatafileWrapper\Datafilewrapper
.vb:line 82
   at CyzFileDump.Program.Main(String[] args) in C:\Users\RB26\git\CyzFile-API\CyzFileDump\Program.cs:line 31
```

I guess there are some assumptions about files having windows style pathnames that we would need to resolve to make the software cross platform.

**Comment by LievaartR** [comment]
Hmm, that is interesting, looking at the prompt, and the command you enter, it is actually using the correct path,
just the windows style, instead of the linux style.

The thing is, the short example program does not do any path manipulation at all, it just passes the string from the command line.
I also notice at the stack trace that is displayed also uses the windows style path names.

So it seems that .net itself is somehow confused about which style of path names it is supposed to use.  So unfortunately no
obvious mistake in the code. 

I will have to setup WSL in here, and see if I can reproduce this.

**Comment by LievaartR** [comment]
Hi Robert,

I just did a quick install of WSL2 on my PC, and cloned and built the example program, and I do not get that error.  (In the latest version of the example program I added auto cropping,
and I do get errors on some OpenCV library when exporting images, #2) 

I can open the file and get particle information from it.  
Can you check which version of WSL you are using?

**Comment by RobBlackwell** [comment]
I just did a `sudo apt update` / `upgrade` and it all now works, so I presume it was a dotnet version problem. I think we can close this issue now. Thanks!

I'm running Ubuntu on WSL2

```
PS C:\Users\RB26> wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         2

```
